# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 020de097cdd67b8c659f694d833192c57600c3369c5b1b57ca9fa722a79545e71d8d7d2f57a5009cee840f4aa97a3ce5c133c1e8cd2d194449c19d7faa6455ab

test:
  secret_key_base: 5be5229208e6afa1d468a68da1a584f1c57e118031443ac6c67bcd8fb2bdacc37c9b0c9f82803288231aaa5dc006cbd273775170c7d1a750aa72943c00f008b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
